### PR TITLE
Added query fee effective cut

### PR DESCRIPTION
**Pull request by juanmardefago**

### CODE REVIEW

**Review by davekaj — APPROVED** [review]
Looks good. Do we have this syncing somewhere?

**Comment by juanmardefago** [comment]
> Looks good. Do we have this syncing somewhere?

@davekaj Yes, https://thegraph.com/explorer/subgraph/juanmardefago/dev-subgraph

**Comment by davekaj** [comment]
Amazing, okay I will merge this to mainnet-staging later today when I deploy the subgraph to the correct endpoint

**Comment by davekaj** [comment]
has been merged into mainnet-staging

**Pull request merged**
