### PR TITLE
Fixed epoch and allocations indexer and delegation index rewards

### PR DESCRIPTION
**Pull request by juanmardefago**
Indexing at my dev-subgraph, it should work since it was a clear typo, but I'll update on the comments when it's ready and tested

### CODE REVIEW

**Review by davekaj — APPROVED** [review]
looks good to me!

**Comment by juanmardefago** [comment]
@davekaj Just checked it here and it seems to be working as expected: https://thegraph.com/explorer/subgraph/juanmardefago/dev-subgraph?query=Epoches

**Comment by davekaj** [comment]
I will redeploy the subgraph on monday :)

**Comment by davekaj** [comment]
https://thegraph.com/explorer/subgraph/graphprotocol/graph-network-mainnet done!

**Pull request merged**
